# Generated by Django 5.0.4 on 2024-04-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_first_name', models.CharField(blank=True, null=True)),
                ('parent_last_name', models.CharField(blank=True, null=True)),
                ('child_first_name', models.CharField(blank=True, null=True)),
                ('child_last_name', models.CharField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, null=True)),
                ('city', models.CharField(blank=True, null=True)),
                ('state', models.CharField(blank=True, null=True)),
                ('zip_code', models.CharField(blank=True, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, null=True)),
                ('send_email', models.BooleanField(blank=True, null=True)),
                ('send_text', models.BooleanField(blank=True, null=True)),
                ('need_financial_aid', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
