# Generated by Django 5.0.4 on 2024-04-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('martialarts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicants',
            new_name='Applicant',
        ),
    ]
