# Generated by Django 5.0.4 on 2024-04-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martialarts', '0002_rename_applicants_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='need_financial_aid',
        ),
        migrations.AddField(
            model_name='applicant',
            name='story',
            field=models.TextField(blank=True, null=True, verbose_name="How will training Martial Arts Improve your child's life?"),
        ),
    ]
