# Generated by Django 5.0.4 on 2024-04-17 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('martialarts', '0003_remove_applicant_need_financial_aid_applicant_story'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicant',
            new_name='FinancialAidApplicant',
        ),
    ]
