# Generated by Django 5.0.4 on 2024-04-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martialarts', '0004_rename_applicant_financialaidapplicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaidapplicant',
            name='household_income',
            field=models.CharField(blank=True, null=True),
        ),
    ]
