# Generated by Django 5.0.4 on 2024-04-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martialarts', '0005_financialaidapplicant_household_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaidapplicant',
            name='aid_awarded',
            field=models.CharField(blank=True, null=True),
        ),
    ]
